export const easyWords = [
  { word: "shovel", hint: "Used for digging soil or snow"},
  { word: "puzzle", hint: "You solve it by putting pieces together" },
  { word: "quarantine", hint: "Isolation to prevent the spread of disease." },
  { word: "pasture", hint: "Land covered with grass for grazing animals."},
  { word: "aviation", hint: "The science or practice of flying aircraft."},
  { word: "pirate", hint: "A person who attacks ships at sea."},
  { word: "monastery", hint: "A place where monks or nuns live."},
  { word: "loki", hint:"I am Asgard's son by name, but not by blood. I deal in tricks more than trust"},
  { word: "mirage", hint: "An illusion seen in deserts"},
  { word: "eclipse", hint: "One heavenly body hides another" },
  { word: "palindrome", hint: "It reads the same forward and backward — no cheating." },
  { word: "kangaroo", hint: "I carry my kid like groceries — but in a built-in bag,'who?'" },
  { word: "owl", hint: "I see when others sleep and ask the same question over and over: 'Who?'" },
  { word: "beetroot", hint: "Stains your hands like blood, sweetens your salad."},
  { word: "neither", hint: "Which is heavier? A ton of bricks or A ton of feathers"},
  { word: "secret", hint: "I'm known by few and guarded by silence."},
  { word: "fog",hint: "I blur your vision, not your thoughts."},
  { word: "jamun",hint: "This purple fruit stains your tongue like royalty."},
  { word: "hulk",hint: "A brilliant scientist having 7 phd degree who transforms into a giant"},
  { word: "deadpool",hint: "A superhero with a healing factor, known for his dark humor."},
  { word: "nobita",hint: "I am a lazy boy who always gets saved by a cat from the future."},
];

export const mediumWords = [
  { word:"venom", hint: "Poison in a fang" },
  { word:"brainfreeze", hint: "Punishment for loving ice cream too fast." },
  { word:"chameleon", hint: "I wear a thousand outfits but carry no wardrobe, 'who?'" },
  { word:"penguin", hint: "I dress for a gala but cannot fly — still, I waddle with style,'who?" },
  { word:"toothbrush",hint:"I am long, stiff, and you put me in your mouth before bed"},
  { word:"lemur", hint: "I dance through the forest like I am in a jungle musical,'who?"},
  { word:"spine",hint: "Without it, you would not stand tall — literally."},
  { word:"bermuda",hint: "A place where legends of lost ships and planes roam."},
  { word:"flute",hint:"You can blow me, stroke me, or use me to play music"},
  { word:"grease", hint:"I am wet, slippery and help things slide smoothly" },
  { word:"atlas",hint: "A collection of maps, named after a titan who held the heavens."},
  { word:"darkness",hint: "The more of this there is , the less you see"},
  { word:"books",hint: "What has words but never speaks?"},
  { word:"roadway", hint:"What goes through cities and towns but never moves?"},
  { word:"footprints",hint: "I say you were here — even when you're long gone."},
  { word:"knock",hint: "I come before entry but never enter myself."},
  { word:"medusa", hint: "Look into my eyes and you're stone cold."},
  { word:"elevator", hint:"You go down on me,then I go up"},
  { word:"balloon",hint:"I am 'big' when you blow me, 'small' when you let me go"},
  { word:"shinchan",hint: "He’s the little rascal who can’t sit still, is always in trouble, and has a talent for embarrassing everyone—especially his parents!"},
  { word:"kara", hint:"I am the last daughter of a lost world!, flying in my cousin's shadow"},
];


export const hardWords = [
  { word: "totem", hint: "A symbolic object of tribes" },
  { word: "oracle", hint: "A person said to predict the future" },
  { word: "riddle", hint: "It asks you, but won't answer"},
  { word: "enigma", hint: "A mystery hard to explain" },
  { word: "zephyr", hint: "A soft breeze with a fancy name"},
  { word: "paradox", hint: "When two truths fight and both win."},
  { word: "jigsaw", hint: "Broken pieces that make a perfect picture."},
  { word: "hullabaloo", hint: "Too much noise over too little."},
  { word: "platypus", hint: "A mammal that lays eggs,'who?"},
  { word: "future", hint: "What is always in front of you but cannot be seen?"},
  { word: "swims",hint:"What word typed in all capital letters can be read the same upside down"},
  { word: "ephemeral",hint: "Exists only for a moment, yet never forgotten."},
  { word: "pandiculation",hint: "The full-body stretch and yawn combo — first thing every morning."},
  { word: "Petrichor",hint: "The pleasant, earthy smell after rain falls on dry ground."},
];
